### PR TITLE
Update to 20.0.0.0beta1

### PR DESCRIPTION
**Pull request by liamharper2453**

### CODE REVIEW

**Comment by tuxuser** [comment]
Thanks, good job!

Please reintroduce 

```
      - uses: marvinpinto/action-automatic-releases@latest
        if: "github.ref == 'refs/heads/master'"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: "Development Build"
          files: |
            ${{github.workspace}}/*.ipk
            ${{github.workspace}}/org.webosbrew.hyperhdr.loader.manifest.json
      - uses: marvinpinto/action-automatic-releases@latest
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{ github.ref_name }}
          files: |
            ${{github.workspace}}/*.ipk
            ${{github.workspace}}/org.webosbrew.hyperhdr.loader.manifest.json
```

then its good to merge

**Comment by liamharper2453** [comment]
> Thanks, good job!
> 
> Please reintroduce
> 
> ```
>       - uses: marvinpinto/action-automatic-releases@latest
>         if: "github.ref == 'refs/heads/master'"
>         with:
>           repo_token: "${{ secrets.GITHUB_TOKEN }}"
>           automatic_release_tag: latest
>           prerelease: true
>           title: "Development Build"
>           files: |
>             ${{github.workspace}}/*.ipk
>             ${{github.workspace}}/org.webosbrew.hyperhdr.loader.manifest.json
>       - uses: marvinpinto/action-automatic-releases@latest
>         if: "startsWith(github.ref, 'refs/tags/v')"
>         with:
>           repo_token: "${{ secrets.GITHUB_TOKEN }}"
>           prerelease: false
>           title: ${{ github.ref_name }}
>           files: |
>             ${{github.workspace}}/*.ipk
>             ${{github.workspace}}/org.webosbrew.hyperhdr.loader.manifest.json
> ```
> 
> then its good to merge
> 
> Actually - lemme do that really quick

Ah yeah sorry I turned that off for testing my fork and didn't put it back in.

Do you think the removal of the flatc/flathash stuff is ok? They didn't seem to be in the HyperHDR build anymore hence why I took it out. But wasn't sure whether it was genuinely removed or I made a mistake. I did see a change around flatc for the build in the most recent HyperHDR commit (https://github.com/awawa-dev/HyperHDR/commit/558c7e03d7da0d52653cd2fe68d96e3634fae227#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR635)

**Comment by tuxuser** [comment]
> Do you think the removal of the flatc/flathash stuff is ok? They didn't seem to be in the HyperHDR build anymore hence why I took it out. But wasn't sure whether it was genuinely removed or I made a mistake. I did see a change around flatc/flathash for the build in the most recent HyperHDR commit ([awawa-dev/HyperHDR@558c7e0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR635](https://github.com/awawa-dev/HyperHDR/commit/558c7e03d7da0d52653cd2fe68d96e3634fae227#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR635))

Looks like only `flathash` got removed, lets try to keep flatc if possible.. we will see soon

**Comment by awawa-dev** [comment]
Currently, if cross-compiling is detected, HyperHDR will use the flatbuffers from its submodule, will build the flatc compiler in the host environment and precompile the HyperHDR flatbuffer templates. Finally, they will be cross-compiled at a later stage using the same version of the flatbuffers from the submodule. Therefore, the host does not need to have its own flat buffers installed anymore.

**Comment by tuxuser** [comment]
> Currently, if cross-compiling is detected, HyperHDR will use the flatbuffers from its submodule, will build the flatc compiler in the host environment and precompile the HyperHDR flatbuffer templates. Finally, they will be cross-compiled at a later stage using the same version of the flatbuffers from the submodule. Therefore, the host does not need to have its own flat buffers installed anymore.

Thanks for the insight!

**Pull request merged**
